site_name: AnimeWorld-API
site_description: UNOFFICIAL library for AnimeWorld
site_url: https://github.com/MainKronos/AnimeWorld-API

theme:
  name: 'material'
  language: en
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  icon:
    repo: fontawesome/brands/github
  logo: static/img/logo.svg
  favicon: static/img/logo.svg
  features:
  - navigation.sections
  - navigation.tracking
  - search.suggest
  - content.code.annotate
  - content.code.copy

repo_name: MainKronos/AnimeWorld-API
repo_url: https://github.com/MainKronos/AnimeWorld-API
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Usage:
      - QuickStart: 'usage/quickstart.md'
      - Advanced Usage: 'usage/advanced.md'
  - API Reference:
      - Developer Interface: 'api-reference/developer-interface.md'
      - Exceptions: 'api-reference/exceptions.md'
  - Community:
      - Contributing: 'community/contributing.md'
      - Code of Conduct: 'community/code-of-conduct.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['docs']
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
- i18n:
    docs_structure: suffix
    fallback_to_default: true
    languages:
      - locale: en
        default: true
        name: English
        build: true
      - locale: it
        name: Italiano
        build: true
- autorefs:
    resolve_closest: true
- git-revision-date-localized:
    type: date 
    locale: en
- search:
    lang: 
    - en
    - it
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: [.]
        options:
          docstring_style: google
          # show_source: false

          show_root_heading: true
          show_root_full_path: false
          # show_category_heading: false
          # show_object_full_path: false
          allow_inspection: true
          group_by_category: true

          show_root_toc_entry: false
          # signature_crossrefs: true ----
          # show_symbol_type_toc: true ----
          
          # docstring_section_style: list
          line_length: 80
          separate_signature: true

          annotations_path: brief

          show_signature: true
          # show_signature_annotations: true

          show_submodules: false
          show_bases: false
          
          merge_init_into_class: true
          filters: ["!^_"]


watch:
- animeworld