site_name: AnimeWorld-API
site_description: UNOFFICIAL library for AnimeWorld
site_url: https://github.com/MainKronos/AnimeWorld-API

theme:
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
    features:
        - navigation.sections

repo_name: MainKronos/AnimeWorld-API
repo_url: https://github.com/MainKronos/AnimeWorld-API
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Usage:
      - QuickStart: 'usage/quickstart.md'
      - Advanced Usage: 'usage/advanced.md'
  - API Reference:
      - Developer Interface: 'api-reference/developer-interface.md'
      - Exceptions: 'api-reference/exceptions.md'
  - Community:
      - Third Party Packages: 'community/third-party-packages.md'
      - Contributing: 'community/contributing.md'
      - Code of Conduct: 'community/code-of-conduct.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences