# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Override PyPI release

on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Versione'
        required: true
      override:
        type: number
        description: 'Override'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Override
      run: |
        for file in dist/*${{ github.event.inputs.version }}*; do
          echo "$file - ${file%%${{github.event.inputs.version}}*}${{ github.event.inputs.version}}-${{github.event.inputs.override}}${file##*${{github.event.inputs.version}}}"
        done

        for file in dist/*${{ github.event.inputs.version }}*; do
          mv -- "$file" "${file%%${{github.event.inputs.version}}*}${{github.event.inputs.version}}-${{github.event.inputs.override}}${file##*${{github.event.inputs.version}}}"
        done
    - name: Publish
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload --skip-existing dist/*
